import type { University } from "@/lib/app-data";

const base = {
  language: "English",
  verified: false,
  website: null,
  created_at: "2026-10-04T00:00:00.000Z",
  updated_at: "2026-10-04T00:00:00.000Z",
};

export const PUBLIC_CATALOGUE: University[] = [
  {
    ...base,
    id: "public-tum",
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    fields: ["Engineering", "Computer Science", "Business"],
    levels: ["UG", "PG"],
    tuition_eur: 0,
    living_eur: 13000,
    min_score: 80,
    min_ielts: 6.5,
    intakes: ["Winter", "Summer"],
    description: "Public research university with strong engineering programmes.",
  },
  {
    ...base,
    id: "public-amsterdam",
    name: "University of Amsterdam",
    country: "Netherlands",
    city: "Amsterdam",
    fields: ["Business", "Psychology", "Computer Science"],
    levels: ["UG", "PG"],
    tuition_eur: 14500,
    living_eur: 14000,
    min_score: 75,
    min_ielts: 6.5,
    intakes: ["September"],
    description: "Large research university with many English-taught programmes.",
  },
  {
    ...base,
    id: "public-delft",
    name: "Delft University of Technology",
    country: "Netherlands",
    city: "Delft",
    fields: ["Engineering", "Architecture", "Computer Science"],
    levels: ["UG", "PG"],
    tuition_eur: 16500,
    living_eur: 12500,
    min_score: 80,
    min_ielts: 6.5,
    intakes: ["September"],
    description: "Technical university known for engineering and design.",
  },
  {
    ...base,
    id: "public-bologna",
    name: "University of Bologna",
    country: "Italy",
    city: "Bologna",
    fields: ["Economics", "Law", "Medicine"],
    levels: ["UG", "PG"],
    tuition_eur: 3000,
    living_eur: 10000,
    min_score: 65,
    min_ielts: 6,
    intakes: ["September"],
    description: "Historic multidisciplinary university in northern Italy.",
  },
  {
    ...base,
    id: "public-trinity",
    name: "Trinity College Dublin",
    country: "Ireland",
    city: "Dublin",
    fields: ["Business", "Computer Science", "Law"],
    levels: ["UG", "PG"],
    tuition_eur: 22000,
    living_eur: 15000,
    min_score: 75,
    min_ielts: 6.5,
    intakes: ["September"],
    description: "Ireland's oldest university with a central Dublin campus.",
  },
  {
    ...base,
    id: "public-lund",
    name: "Lund University",
    country: "Sweden",
    city: "Lund",
    fields: ["Engineering", "Business", "Science"],
    levels: ["UG", "PG"],
    tuition_eur: 15000,
    living_eur: 11000,
    min_score: 75,
    min_ielts: 6.5,
    intakes: ["August", "January"],
    description: "Swedish research university with broad international programmes.",
  },
];
